# Generated by Django 5.0.2 on 2024-02-15 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(db_index=True, help_text='Day number (1-24)', unique=True)),
                ('title', models.CharField(help_text='Title of the Advent Day', max_length=255)),
                ('description', models.TextField(help_text='Description of the Advent Day')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_number', models.PositiveSmallIntegerField(choices=[(1, 'Task 1'), (2, 'Task 2')], help_text='Task number (1 or 2)')),
                ('description', models.TextField(help_text='Description of the task')),
                ('advent_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='adventofcode.adventday')),
            ],
            options={
                'ordering': ['advent_day__day_number', 'task_number'],
                'unique_together': {('advent_day', 'task_number')},
            },
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('test', 'Test'), ('full', 'Full')], help_text='Type of input data (test or full)', max_length=4)),
                ('data', models.TextField(help_text='The input data for the task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_data', to='adventofcode.task')),
            ],
            options={
                'unique_together': {('task', 'input_type')},
            },
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_number', models.PositiveIntegerField(help_text='Sequential number of the tick for the input data')),
                ('state_description', models.TextField(help_text='Description of the state at this tick')),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='adventofcode.inputdata')),
            ],
            options={
                'ordering': ['input_data__task__advent_day__day_number', 'input_data__task__task_number', 'tick_number'],
                'unique_together': {('input_data', 'tick_number')},
            },
        ),
    ]
