# Generated by Django 5.0.2 on 2024-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventofcode', '0002_inputdata_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tick',
            name='state_description',
        ),
        migrations.AddField(
            model_name='tick',
            name='endstate',
            field=models.TextField(default='{}', help_text='The state and actions from this tick'),
        ),
    ]
